### ISSUE TITLE
https://vgb.purplekingdomgames.com offline

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/gloomhaven-board#97]
sorry don't know how else report a problem but the main virtual map is offline.  we are getting an error with the following text

We encountered an error when trying to load your application and your page could not be served. Check the logs for your application in the App Platform dashboard.

**Comment by cafelizardo** [comment]
problem appears to be resolved later that day.  Any idea what happened?

**Comment by hobnob** [comment]
Very odd - I'll have a look into it and see if tehre's anything I can do to stop it happening again. I've not changed anything so it should have just been working as expected :-/

**Comment by hobnob** [comment]
Hmmmm... no insight as to why this happened... I can see the CPU drop to 0 for a few days, which suggests that the app was down for quite some time, but no actual logging that suggests why that might be. I've set up an email alert so that if it happens again I'll at least get alerted, and can jump on to see it happening in real time. Hopefully this is just a one-off 🤞
